
name: Testing pipeline

on:
  push: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: package
      run: |
        python setup.py install
        pip install .
      
    - name: test
      run: |
        pytest Tests/

 